const INSERIR = 'INSERIR'
const INSERT_TEXT_IN_SEARCH = 'INSERT_TEXT_IN_SEARCH'
const REFRESH_RESULTS_OF_SEARCH = 'REFRESH_RESULTS_OF_SEARCH'

export { INSERIR, INSERT_TEXT_IN_SEARCH, REFRESH_RESULTS_OF_SEARCH } 