const INSERT_TEXT_IN_SEARCH = 'INSERT_TEXT_IN_SEARCH'
const REFRESH_RESULTS_OF_SEARCH = 'REFRESH_RESULTS_OF_SEARCH'
const CHANGE_USER = 'CHANGE_USER'
const CHANGE_MID_COMPONENT = 'CHANGE_MID_COMPONENT'
const SET_OPTION_SEARCH = 'SET_OPTION_SEARCH'

export { 
    INSERT_TEXT_IN_SEARCH, 
    REFRESH_RESULTS_OF_SEARCH, 
    CHANGE_USER,
    CHANGE_MID_COMPONENT,
    SET_OPTION_SEARCH
}