const INSERT_TEXT_IN_SEARCH = 'INSERT_TEXT_IN_SEARCH'
const REFRESH_RESULTS_OF_SEARCH = 'REFRESH_RESULTS_OF_SEARCH'
const CHANGE_USER = 'CHANGE_USER'
const CHANGE_MID_COMPONENT = 'CHANGE_MID_COMPONENT'
const SET_OPTION_SEARCH = 'SET_OPTION_SEARCH'
const SET_CURRENT_MUSIC = 'SET_CURRENT_MUSIC'
const SET_VOLUME = 'SET_VOLUME'
const SET_CURRENT_MUSIC_LIKED = 'SET_CURRENT_MUSIC_LIKED'
const SET_SHUFFLE_MODE = 'SET_SHUFFLE_MODE'
const SET_REPEAT_MODE = 'SET_REPEAT_MODE'
const SET_IS_LOGGED = 'SET_IS_LOGGED'


export { 
    INSERT_TEXT_IN_SEARCH, 
    REFRESH_RESULTS_OF_SEARCH, 
    CHANGE_USER,
    CHANGE_MID_COMPONENT,
    SET_OPTION_SEARCH,
    SET_CURRENT_MUSIC,
    SET_VOLUME,
    SET_CURRENT_MUSIC_LIKED,
    SET_SHUFFLE_MODE,
    SET_REPEAT_MODE,
    SET_IS_LOGGED
}